time_limit: 12600
sleep_time: 0.1
wp_radius: 15
pwm_range: 400 #1500 +/- pwm_range <- MAX 400
P: 0.1
I: 0.0
D: 0.0
gpio:
  mode:
    in: 4
    out: null
  servo:
    in: 17
    out: 23
  thruster:
    in: 27
    out: 24
  or:
    in: 16
    out: null
waypoints:
  -
    name: "wp1"
    lat: 35.714963
    lon: 139.759404
  -
    name: "wp2"
    lat: 35.713878 
    lon: 139.760186
  -
    name: "wp3"
    lat: 35.714798 
    lon: 139.760400
